### ISSUE TITLE
Title Issue

### ISSUE THREAD

**Issue by ZoteroUser-alt** [RoadToDream/ZotMeta#11]
Not sure if this occurred before Zotero update but title is shortened after colon. 
Example "Sex Differences in Outcomes After STEMI: Effect Modification by Treatment Strategy and Age"
After (Update Metadata): "Sex Differences in Outcomes After STEMI"

If anyone has a solution or an update can be provided, this would be much appreciated. 

Thanks to the creator.

**Comment by RoadToDream** [comment]
Fixed with v2.0. Thanks for the info.

**Comment by VetleHvoslef** [comment]
Hey I'm currently on ZotMeta version 2.0 and this issue still happens to me. For example it shortened this title:
Gravity: an introduction to Einstein's general relativity
into this:
Gravity

**Comment by RoadToDream** [comment]
> Hey I'm currently on ZotMeta version 2.0 and this issue still happens to me. For example it shortened this title: Gravity: an introduction to Einstein's general relativity into this: Gravity

Hi @VetleHvoslef , the fix was only for journal, not for isbn. will add an option for customize
